name: accelerator-env
channels:
  - conda-forge
dependencies:
  - libprotobuf<6
  - python>=3.9,<3.11
  - pip
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - torchaudio==2.6.0
      - deepdiff
      - xonsh
      - openpyxl
      - git+https://github.com/mflowgen/mflowgen.git@69412255acc2c509e98105804e5a97d9738ddfe1#egg=mflowgen
      - pandas
      - compiledb
      - -e voyager-compiler
      - -e interstellar
